channels = ["anaconda", "conda-forge"]
[deps]
# Conda package names and versions
python = ">=3.5,<4"

# CondaPkg uses mamba by default
fooof = ">=1.0, <2"

[pip.deps]
# Pip package names and versions
