name: CI
concurrency:
  group: ${{ github.head_ref }}.ci
  cancel-in-progress: true
on:
  push:
      paths-ignore:
        - 'README.md'
      branches:
        - main
  pull_request:
      paths-ignore:
        - 'README.md'
      branches:
        - main
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1'
          - 'min'
          - 'nightly'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v5
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@fdcc8476540edceab3de004e990f80d881c6cc00 # v5.5.0
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          
